replicaCount: 2

image:
  repository: curiopay/api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: api.curiopay.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  port: 3000
  nodeEnv: production
  apiPrefix: /api
  swaggerPath: /docs
  logLevel: info

# Enable PostgreSQL deployment
postgresql:
  enabled: true
  auth:
    username: curiopay
    password: curiopay-password
    database: curiopay
  primary:
    persistence:
      enabled: true
      size: 8Gi
  
# Prisma migration job configuration
prisma:
  enabled: true
  image: 
    repository: curiopay/api
    tag: latest
  migrate:
    command: ["npx", "prisma", "migrate", "deploy"]
  generateClient:
    command: ["npx", "prisma", "generate"]
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation 