apiVersion: apps/v1
kind: Deployment
metadata:
  name: curiopay-api
  labels:
    app: curiopay-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curiopay-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: curiopay-api
    spec:
      containers:
      - name: curiopay-api
        image: curiopay/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - configMapRef:
            name: curiopay-api-config
        - secretRef:
            name: curiopay-api-secrets 