name: Test Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t curiopay-api-test .

      - name: Run container and check health
        run: |
          docker run -d --name curiopay-api-test -p 3000:3000 curiopay-api-test
          sleep 10
          docker ps | grep curiopay-api-test
          docker logs curiopay-api-test 