apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: curiopay-staging

resources:
  - ../../base
  - sealed-secrets.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

commonLabels:
  environment: staging 